/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as AppRouteImport } from './routes/_app/route'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AppIndexImport } from './routes/_app/index'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings/route'
import { Route as AppUserRouteImport } from './routes/_app/_user/route'
import { Route as AdminSettingsIndexImport } from './routes/admin/settings/index'
import { Route as AdminProductsIndexImport } from './routes/admin/products/index'
import { Route as AppCartIndexImport } from './routes/_app/cart/index'
import { Route as AdminSettingsAppearanceImport } from './routes/admin/settings/appearance'
import { Route as AdminProductsIdImport } from './routes/admin/products/$id'
import { Route as AppProductsIdImport } from './routes/_app/products.$id'
import { Route as AppCartCheckoutImport } from './routes/_app/cart/checkout'
import { Route as AppUserProfileIndexImport } from './routes/_app/_user/profile/index'

// Create/Update Routes

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminSettingsRouteRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AppUserRouteRoute = AppUserRouteImport.update({
  id: '/_user',
  getParentRoute: () => AppRouteRoute,
} as any)

const AdminSettingsIndexRoute = AdminSettingsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)

const AdminProductsIndexRoute = AdminProductsIndexImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AppCartIndexRoute = AppCartIndexImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AdminSettingsAppearanceRoute = AdminSettingsAppearanceImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)

const AdminProductsIdRoute = AdminProductsIdImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AppProductsIdRoute = AppProductsIdImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppCartCheckoutRoute = AppCartCheckoutImport.update({
  id: '/cart/checkout',
  path: '/cart/checkout',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppUserProfileIndexRoute = AppUserProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppUserRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/_app/_user': {
      id: '/_app/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppUserRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/_app/cart/checkout': {
      id: '/_app/cart/checkout'
      path: '/cart/checkout'
      fullPath: '/cart/checkout'
      preLoaderRoute: typeof AppCartCheckoutImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/products/$id': {
      id: '/_app/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AppProductsIdImport
      parentRoute: typeof AppRouteImport
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/settings/appearance': {
      id: '/admin/settings/appearance'
      path: '/appearance'
      fullPath: '/admin/settings/appearance'
      preLoaderRoute: typeof AdminSettingsAppearanceImport
      parentRoute: typeof AdminSettingsRouteImport
    }
    '/_app/cart/': {
      id: '/_app/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AppCartIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexImport
      parentRoute: typeof AdminSettingsRouteImport
    }
    '/_app/_user/profile/': {
      id: '/_app/_user/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppUserProfileIndexImport
      parentRoute: typeof AppUserRouteImport
    }
  }
}

// Create and export the route tree

interface AppUserRouteRouteChildren {
  AppUserProfileIndexRoute: typeof AppUserProfileIndexRoute
}

const AppUserRouteRouteChildren: AppUserRouteRouteChildren = {
  AppUserProfileIndexRoute: AppUserProfileIndexRoute,
}

const AppUserRouteRouteWithChildren = AppUserRouteRoute._addFileChildren(
  AppUserRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppUserRouteRoute: typeof AppUserRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCartCheckoutRoute: typeof AppCartCheckoutRoute
  AppProductsIdRoute: typeof AppProductsIdRoute
  AppCartIndexRoute: typeof AppCartIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppUserRouteRoute: AppUserRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCartCheckoutRoute: AppCartCheckoutRoute,
  AppProductsIdRoute: AppProductsIdRoute,
  AppCartIndexRoute: AppCartIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AdminSettingsRouteRouteChildren {
  AdminSettingsAppearanceRoute: typeof AdminSettingsAppearanceRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsAppearanceRoute: AdminSettingsAppearanceRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AppUserRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/cart/checkout': typeof AppCartCheckoutRoute
  '/products/$id': typeof AppProductsIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/cart': typeof AppCartIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/profile': typeof AppUserProfileIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AppUserRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/cart/checkout': typeof AppCartCheckoutRoute
  '/products/$id': typeof AppProductsIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/cart': typeof AppCartIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/profile': typeof AppUserProfileIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_app/_user': typeof AppUserRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/cart/checkout': typeof AppCartCheckoutRoute
  '/_app/products/$id': typeof AppProductsIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/_app/cart/': typeof AppCartIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/_app/_user/profile/': typeof AppUserProfileIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/admin'
    | '/admin/settings'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/admin/'
    | '/cart/checkout'
    | '/products/$id'
    | '/admin/products/$id'
    | '/admin/settings/appearance'
    | '/cart'
    | '/admin/products'
    | '/admin/settings/'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/admin'
    | '/cart/checkout'
    | '/products/$id'
    | '/admin/products/$id'
    | '/admin/settings/appearance'
    | '/cart'
    | '/admin/products'
    | '/admin/settings'
    | '/profile'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/_app/_user'
    | '/admin/settings'
    | '/auth/login'
    | '/auth/register'
    | '/_app/'
    | '/admin/'
    | '/_app/cart/checkout'
    | '/_app/products/$id'
    | '/admin/products/$id'
    | '/admin/settings/appearance'
    | '/_app/cart/'
    | '/admin/products/'
    | '/admin/settings/'
    | '/_app/_user/profile/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/admin",
        "/auth/login",
        "/auth/register"
      ]
    },
    "/_app": {
      "filePath": "_app/route.tsx",
      "children": [
        "/_app/_user",
        "/_app/",
        "/_app/cart/checkout",
        "/_app/products/$id",
        "/_app/cart/"
      ]
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/settings",
        "/admin/",
        "/admin/products/$id",
        "/admin/products/"
      ]
    },
    "/_app/_user": {
      "filePath": "_app/_user/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_user/profile/"
      ]
    },
    "/admin/settings": {
      "filePath": "admin/settings/route.tsx",
      "parent": "/admin",
      "children": [
        "/admin/settings/appearance",
        "/admin/settings/"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/_app/cart/checkout": {
      "filePath": "_app/cart/checkout.tsx",
      "parent": "/_app"
    },
    "/_app/products/$id": {
      "filePath": "_app/products.$id.tsx",
      "parent": "/_app"
    },
    "/admin/products/$id": {
      "filePath": "admin/products/$id.tsx",
      "parent": "/admin"
    },
    "/admin/settings/appearance": {
      "filePath": "admin/settings/appearance.tsx",
      "parent": "/admin/settings"
    },
    "/_app/cart/": {
      "filePath": "_app/cart/index.tsx",
      "parent": "/_app"
    },
    "/admin/products/": {
      "filePath": "admin/products/index.tsx",
      "parent": "/admin"
    },
    "/admin/settings/": {
      "filePath": "admin/settings/index.tsx",
      "parent": "/admin/settings"
    },
    "/_app/_user/profile/": {
      "filePath": "_app/_user/profile/index.tsx",
      "parent": "/_app/_user"
    }
  }
}
ROUTE_MANIFEST_END */
